project_name: kubectl-debug
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  binary: kubectl-debug
  main: ./cmd/plugin/main.go
  goos:
    - freebsd
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - 386
  ignore:
    - goos: darwin
      goarch: 386
  ldflags:
    - -s -w -X 'github.com/cnzf1/kubectl-debug/version.gitVersion={{.Version}}'
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
  github:
    owner: cnzf1
    name: homebrew-tap
  commit_author:
    name: cnzf1
    email: rayingecho@gmail.com
  install: |
    bin.install "kubectl-debug"
  homepage: "https://www.github.com/cnzf1/kubectl-debug"
  description: "Debug your pod by a new container with every troubleshooting tools pre-installed"
